version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: /usr/bin/pwd
      timeout: 180
  AfterInstall:
    - location: /usr/bin/pwd
      timeout: 180
  ValidateService:
    - location: /usr/bin/pwd
      timeout: 3600
      runas: codedeployuser
  ApplicationStop:
    - location: /usr/bin/ls -al /opt
      timeout: 3600
      runas: codedeployuser
  ApplicationStart:
    - location: /usr/bin/ls -al /opt
      timeout: 3600
      runas: codedeployuser

