version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
  build:
    commands:
     - echo Building the Docker image...
  post_build:
    commands: 
      - echo Pushing the Docker images...
      - echo "find the Way"
